### ISSUE TITLE
Use LF line endings

### ISSUE THREAD

**Issue by timjb** [bradleyayers/getdocs2ts#13]
Currently, the generated code has CRLF line endings, because that is what [string-builder](https://www.npmjs.com/package/string-builder) uses.

I think we should get rid of `StringBuilder` and just return strings directly.

**Comment by bradleyayers** [comment]
Using a string builder is nice pattern for performance, we could just switch to [stringbuilder](https://www.npmjs.com/package/stringbuilder) which allows line endings to be configured.
