### ISSUE TITLE
dom.* naming conflict

### ISSUE THREAD

**Issue by bradleyayers** [bradleyayers/getdocs2ts#8]
There's a naming conflict in `prosemirror-model`, where we need `dom.Node` for `DOMOutputSpec`, but we have `Node` defined as a class which shadows the global lib definition.

The work-around I've been using is to create a sibling `dom.d.ts` file:

```
export type DOMDataTransfer = DataTransfer;
export type DOMDocument = Document;
export type DOMElement = HTMLElement;
export type DOMEvent = Event;
export type DOMFragment = DocumentFragment;
export type DOMKeyboardEvent = KeyboardEvent;
export type DOMMouseEvent = MouseEvent;
export type DOMMutationRecord = MutationRecord;
export type DOMNode = Node;

export {
  DOMDataTransfer as DataTransfer,
  DOMDocument as Document,
  DOMElement as Element,
  DOMEvent as Event,
  DOMFragment as DocumentFragment,
  DOMKeyboardEvent as KeyboardEvent,
  DOMMouseEvent as MouseEvent,
  DOMMutationRecord as MutationRecord,
  DOMNode as Node,
};
```

This is then used in the prosemirror-model `index.d.ts` types:

```
import * as dom from './dom';

// ...

export type DOMOutputSpec
    = string
    | dom.Node
    | DOMOutputSpecArray;
```

**Comment by bradleyayers** [comment]
/cc @timjb any ideas for how we should approach this? If the sibling file is needed, we probably want a mechanism to contribute other files to a definition, basically like a sidecar definition that can be used to avoid naming conflicts.

If the sidecar module isn't needed, I'm interested in the syntax to make that work?

**Comment by timjb** [comment]
Maybe we can instead rename the classes in the generated code instead of the DOM types to avoid name clashes.

In the generated file for `prosemirror-model`:

```typescript
class ProsemirrorNode { ... }

export { ProsemirrorNode as Node }
```

And in all the files that import `prosemirror-model`:

```typescript
import { Node as ProsemirrorNode } from 'prosemirror-model'
```

**Comment by bradleyayers** [comment]
I'm okay with either way. For readability I prefer the `dom.d.ts` approach (since it has more of a 1-1 correspondence with ProseMirror's source), but your proposal should be easier to integrate into getdocs2ts.
